services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./client
    command: npm run start
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
    ports:
      - "3000:3000"
  